@startuml

participant "Server" as Server

participant "Fifo" as Fifo
participant "IFifoWrite" as IFifoWrite
participant "FifoWriteQ" as QFifoWrite
participant "queue" as queue
participant "FifoWriteDirect" as NQFifoWrite



Server->Fifo: void write(ConnectionId  id, const void* data, size_t sizeInBytes)
activate Fifo


Fifo -> IFifoWrite: write(const void* data, size_t sizeInBytes)
activate IFifoWrite

IFifoWrite->QFifoWrite: write(const void* data, size_t sizeInBytes)
QFifoWrite ->queue: write(const void* data, size_t sizeInBytes)
queue->channel: data


@enduml